# Generated by Django 3.2.6 on 2023-09-04 14:28

import csv_manager.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=csv_manager.models.csv_upload_path)),
                ('source_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enriched_instances', to='csv_manager.csvfile')),
            ],
        ),
        migrations.CreateModel(
            name='EnrichDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(help_text='The origin URL which was used to enrich')),
                ('external_response', models.JSONField()),
                ('source_column', models.TextField(help_text='Merged column selected from CSVFile')),
                ('selected_key', models.TextField(help_text='Selected json key to be used to merge with CSVFile')),
                ('enrich_level', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrich_detail', to='csv_manager.csvfile')),
            ],
        ),
    ]
