# Generated by Django 3.2.6 on 2023-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='original_file_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
