# Generated by Django 3.2.6 on 2023-09-06 13:31

import csv_manager.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_manager', '0002_csvfile_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichdetail',
            name='status',
            field=models.CharField(choices=[(csv_manager.enums.EnrichmentStatus['IN_PROGRESS'], 'in_progress'), (csv_manager.enums.EnrichmentStatus['FINISHED'], 'finished'), (csv_manager.enums.EnrichmentStatus['FAILED'], 'failed')], default=csv_manager.enums.EnrichmentStatus['IN_PROGRESS'], help_text='Status of process of enrichment csv file', max_length=50),
        ),
    ]
