# Generated by Django 3.2.6 on 2023-09-12 08:31

import csv_manager.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_manager', '0002_alter_enrichdetail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrichdetail',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='enrichdetail',
            name='status',
            field=models.CharField(choices=[('initiated', 'INITIATED'), ('fetching_response', 'FETCHING_RESPONSE'), ('failed_fetching_response', 'FAILED_FETCHING_RESPONSE'), ('failed_fetching_response_incorrect_url_status', 'FAILED_FETCHING_RESPONSE_INCORRECT_URL_STATUS'), ('failed_fetching_response_other_request_exception', 'FAILED_FETCHING_RESPONSE_OTHER_REQUEST_EXCEPTION'), ('failed_fetching_response_not_json', 'FAILED_FETCHING_RESPONSE_NOT_JSON'), ('failed_fetching_response_empty_json', 'FAILED_FETCHING_RESPONSE_EMPTY_JSON'), ('awaiting_column_selection', 'AWAITING_COLUMN_SELECTION'), ('failed_column_selection', 'FAILED_COLUMN_SELECTION'), ('enriching', 'ENRICHING'), ('failed_enriching', 'FAILED_ENRICHING'), ('completed', 'COMPLETED')], default=csv_manager.enums.EnrichmentStatus['INITIATED'], help_text='Status of process of enrichment csv file', max_length=50),
        ),
    ]
