from typing import Any, List

from sentry_sdk.integrations import Integration

class Scope:
    def __enter__(self) -> Any: ...
    def __exit__(self, type: Any, value: Any, traceback: Any) -> None: ...
    def set_tag(self, key: str, value: str) -> None: ...

def configure_scope() -> Scope: ...
def capture_message(error: str, level: str) -> None: ...
def init(dsn: str, integrations: List[Integration]) -> None: ...
