from typing import Any

def fromcsv(source: str, *args: Any, **kwargs: Any) -> dict[str, list[Any]]: ...
def data(table: dict[str, list[Any]]) -> list[list[Any]]: ...
def nrows(table: Any) -> int: ...
def header(table: Any) -> tuple[str]: ...
def rowslice(
    table: dict[str, list[Any]], start: int, end: int
) -> dict[str, list[Any]]: ...
