[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py310']  # it must be 3.10
#TODO fix that as structure is not correctly provided
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | dynamic
  | usr
  | dynamic
  | migrations
  | node_modules
  | venv
)/
'''

# https://beta.ruff.rs/docs/configuration/
[tool.ruff]
select = [
    "E",  # pycodestyle error
    "F",  # pyflakes
    "T20",  # flake8-print
    "UP",  # pyupgrade
    "W",  # pycodestyle warnings
]

ignore = [
    'E501', #  Line too long
    'F541', #  f-string without any placeholders
    'E741', #  Ambiguous variable name
]

exclude = [
    '.git',
    'collectedstatic',
    'dynamic',
    # These are checked separately within each integration as they use
    # different python versions
    'node_modules',
    'static',
    'stubs',
    'venv',
]

target-version = "py311"

[tool.ruff.per-file-ignores]
# These files are generated by django and should probably not be modified
"*/migrations/*.py" = ["F401"]
"transformer/*.py" = ["F403", "F405"]
"transformer/settings.py" = ["F401"]

